apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tj9b3f998-go 
  janus-idp.io/tekton: tj9b3f998-go
  backstage.io/kubernetes-id: tj9b3f998-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tj9b3f998-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml