apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tj9b3f998-go
  janus-idp.io/tekton: tj9b3f998-go
  backstage.io/kubernetes-id: tj9b3f998-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tj9b3f998-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
