apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tj9b3f998-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tj9b3f998-go 
  name: tj9b3f998-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tj9b3f998-go 
